### ISSUE TITLE
Mal cálculo del IMC

### ISSUE THREAD

**Issue by gaelceart** [gaelceart/ml-diabetes#1]
Si el peso está en kilogramos, la estatura debe estar representada en metros, no en centímetros.
Si medís 175cm, se debería convertir a 1,75m ya que si se realiza el cálculo con los centímetros el resultado sería muy pequeño.
Ejemplos: 
80kg / (175cm)² ≈ 0,002 ❌
80kg/ (1,75m)² = 26,12 ✅

**Comment by Leandr0Fr** [comment]
Un adelantado a su epoca.
